#!/bin/sh

# Docker entrypoint script for StockyWeb
# Generates runtime configuration from environment variables

set -e

# Default values (matching build-time defaults)
API_BASE_URL=${RUNTIME_API_BASE_URL:-${VITE_API_BASE_URL:-"https://localhost:8000/api/v1"}}
APP_NAME=${RUNTIME_APP_NAME:-${VITE_APP_NAME:-"StockyWeb"}}
APP_VERSION=${RUNTIME_APP_VERSION:-${VITE_APP_VERSION:-"0.0.1"}}
ENABLE_ANALYTICS=${RUNTIME_ENABLE_ANALYTICS:-${VITE_ENABLE_ANALYTICS:-"false"}}
ENABLE_DEBUG=${RUNTIME_ENABLE_DEBUG:-${VITE_ENABLE_DEBUG:-"false"}}
ENABLE_HTTPS_ONLY=${RUNTIME_ENABLE_HTTPS_ONLY:-${VITE_ENABLE_HTTPS_ONLY:-"true"}}
ENVIRONMENT=${RUNTIME_ENVIRONMENT:-${VITE_ENVIRONMENT:-"production"}}

echo "🔧 Generating runtime configuration..."
echo "  API Base URL: $API_BASE_URL"
echo "  App Name: $APP_NAME"
echo "  App Version: $APP_VERSION"
echo "  Environment: $ENVIRONMENT"

# Generate config.js file
cat > /usr/share/nginx/html/config.js << EOF
// Runtime configuration generated at container startup
// This file is automatically generated - do not edit manually
window.APP_CONFIG = {
  apiBaseUrl: "$API_BASE_URL",
  appName: "$APP_NAME", 
  appVersion: "$APP_VERSION",
  enableAnalytics: $ENABLE_ANALYTICS,
  enableDebug: $ENABLE_DEBUG,
  enableHttpsOnly: $ENABLE_HTTPS_ONLY,
  environment: "$ENVIRONMENT"
};

console.log("🚀 Runtime configuration loaded:", window.APP_CONFIG);
EOF

echo "✅ Runtime configuration generated successfully"

# Debug: Show the generated config.js content
echo "🔍 DEBUG - Generated config.js content:"
cat /usr/share/nginx/html/config.js

# Start nginx
echo "🌐 Starting nginx..."
exec nginx -g 'daemon off;'